### ISSUE TITLE
[OSX only] Opening Mineways from MCPrep on a Mac prevents loading worlds

### ISSUE THREAD

**Issue by TheDuckCow** [Moo-Ack-Productions/MCprep#133]
This is a niche known issue, only affecting Mac OSX users who try to open Mineways through MCprep (inside Blender).

If a user tries to open Mineways from a mac, AND the user has wine installed (which is required), the interface will appear to popup correctly. However, when the user goes to load a world, the progress bar does not complete. On the same system and pointing to the same executable, running `wine mienways32.exe` will work fine including post-world loading.

I am not yet sure why this happens, but is not directly due to code within MCprep since Mineways itself does still appear to properly start up and is initially interactive. There could be some issue with the forked process and the environment variables that wine or mineways expects.

**Comment by TheDuckCow** [comment]
Minor update, added [this video demo](https://youtu.be/j4Ib18ROvtI) of the issue.

**Comment by StandingPadAnimations** [comment]
Old issue, but I don't think we should be suggesting WINE as a general solution. Since WINE is just a compatibility layer for Windows executables, it also can in theory (and in practice has in some cases) open UNIX systems to Windows malware. The risk is not worth it in my opinion especially since jmc2obj is in many ways a better alternative to Mineways

**Comment by StandingPadAnimations** [comment]
Closing this since I feel that most Mac users won't/shouldn't be using Mineways through WINE (and I say that as someone who uses WINE a lot). These days, jmc2OBJ is pretty much equal in support to Mineways on our end.
