### ISSUE TITLE
fixed BoxScape Studios villager rig

### ISSUE THREAD

**Issue by Roni-Raihan** [Moo-Ack-Productions/MCprep#430]
### Name of asset submission

rig villager
[villager.zip](https://github.com/TheDuckCow/MCprep/files/11705003/villager.zip)

### Quality checks

- [X] I have used only vanilla textures (or created images that are derived from vanilla textures)
- [X] This is a vanilla minecraft asset/mob/effect
- [X] I have verified my asset has the correct scale (1 Blender unit = 1 meter), and the scale has been applied (control+a, scale)
- [X] If my asset includes a rig, I certified there is a "root" or "main" bone, and the rig object name ends with the name ".arma" or ".rig" to work well with MCprep
- [X] I am the sole creator of this rig, other than any textures by Mojang. Any custom textures I created myself.

### Describe any usage details

This rig is a modified villager rig in mcprep from BoxScape Studios. I only try fix the hand. so I guess credit still has to go to BoxScape Studios

### What name should we use to credit you in the README.md file?

This rig is a modified villager rig in mcprep from BoxScape Studios. I only try fix the hand. so I guess credit still has to go to BoxScape Studios

### Confirmation

- [X] By submitting this asset, I affirm the asset is of my own creation. I understand this asset will be included with MCprep with a CC-BY (attribution) license agreement, and that users of MCprep should refer to [MCprep's readme](https://github.com/TheDuckCow/MCprep#credit) for credit or directly name me for credit when this rig is used.

**Comment by TheDuckCow** [comment]
FYI I've created this updated version, which does some additional fixes:

- last saved version is blender 2.80, this is important for backwards compatibility
- Made two primary materials: one that has SSS, one that doesn't
- Fixed eyes so that if someone does prep materials, they go to the eye texture color instead of white
- Reset so the collection center point is at the base bone's center point (was offset slightly before)

[villager - Boxscape.blend.zip](https://github.com/Moo-Ack-Productions/MCprep/files/12472188/villager.-.Boxscape.blend.zip)

Might be good to sanity check that I didn't break anything with this update! But if you find this file ok now, we're good to call this submission confirmed.

**Comment by Roni-Raihan** [comment]
Tried in versions 2.8 and 3.0. both work fine. And tried installing it on the mob spawner, it also worked well
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/82071318/93c32fd5-8adc-483c-91e9-792bf7993ff8)

**Comment by TheDuckCow** [comment]
Great thanks for testing! Closing this, as the rig will be included in the update.
