### ISSUE TITLE
Importing mods models

### ISSUE THREAD

**Issue by BoBikDied** [Moo-Ack-Productions/MCprep#457]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When attempting to import a JSON model from mods (specifically from the mod "Create"), the following error was displayed:
https://drive.google.com/file/d/1lkH1f8-m7b3FOLLsRjINtaaXeNKfC89C/view?usp=sharing

### What steps are needed to produce the bug?

1) File - Import - .json
2)Import .json model from mod

### What version of MCprep are you using?

MCprep 3.4.3

### What version of Blender are you using?

I tried to do this on different versions of Blender(3.3 - 3.6)

**Comment by StandingPadAnimations** [comment]
From the error, it seems like the texture couldn't be found in the default resource pack (all vanilla textures). Modded blocks aren't supported at the moment, unless you add their textures with the proper name into the MCprep resource pack folder.

**Comment by zNightlord** [comment]
Beside the mod stuffs, this also addressed something else.
I think it shouldn't raise that texture exception, since this is from import from json *2 operators shared the same code also the same add_material* before #398 it didn't raise anything *as far as i remember it* and let the user manually assign the textures, unless we treat this unfindable/ empty texture as a bug rather a feature.

**Comment by StandingPadAnimations** [comment]
The exception is raised because MCprep checks textures based on block name, which in turn is derived from material name (there's also a JSON file for material names to blocks):
https://github.com/Moo-Ack-Productions/MCprep/blob/master/MCprep_addon/materials/generate.py#L116-L123

As far as I can tell, JSON models should define textures anyway, so no need to mess with all global textures (which is overwritten during updates). Modded blocks however will always be a weird area because there's simply too many mods, so I think it's best if we don't support modded blocks explicitly (any support MCprep appears to have will entirely be unintentional)

**Comment by zNightlord** [comment]
> The exception is raised because MCprep checks textures based on block name, which in turn is derived from material name (there's also a JSON file for material names to blocks):
> 
> https://github.com/Moo-Ack-Productions/MCprep/blob/master/MCprep_addon/materials/generate.py#L116-L123
> 
> As far as I can tell, JSON models should define textures anyway, so no need to mess with all global textures (which is overwritten during updates). Modded blocks however will always be a weird area because there's simply too many mods, so I think it's best if we don't support modded blocks explicitly (any support MCprep appears to have will entirely be unintentional)

Yes, I'm aware of that and mentioned 2 things share the same code, one for block in vanilla and this, the thing is json importer shouldn't depend on the main global resource pack. 

The behavior before for **json importer** should be is can't find valid texture for json, leave it empty. So if the user know what that texture is manually reassign it.
https://github.com/Moo-Ack-Productions/MCprep/blob/b741d2bf8f9863d03aa89f1f90506e62dabcbf9c/MCprep_addon/spawner/mcmodel.py#L113
I wouldn't label it as modded block rather geometry that is in a correct json structure to import. 
Java modded blocks using the same system as what vanilla resourcepack no mod, if you look inside the mod resources it contains that similiar resourcepack assets path so.

**Comment by StandingPadAnimations** [comment]
Ahh, `mcmodel` uses its own function for materials. In that case, I would have a popup with the following:
```
The JSON file you are importing is referring to a texture that is not in 
vanilla Minecraft, would you like to import the model without textures 
and handle it yourself?

[YES] [NO]
```

And let the user edit the material to have a texture. Sure, it means they'll have to be somewhat comfortable with nodes, but that's expected from Blender users anyway. It also means a user could use texture painting, if they so wished.

**Comment by zNightlord** [comment]
This should import without raising error now so. Close.
