### ISSUE TITLE
Materials don't generate in EEVEE Next 

### ISSUE THREAD

**Issue by Aspirata** [Moo-Ack-Productions/MCprep#583]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When I set the rendering engine to eevee next, the materials just don't get created properly. Fun fact: if I switch to eevee legacy or cycles > spawn a block or item, and then switch the rendering engine back to eevee next, everything works fine

![image](https://github.com/Moo-Ack-Productions/MCprep/assets/102383379/6eb69154-7038-410e-90a4-f1044e29b676)

### What steps are needed to produce the bug?

Download Bledner 4.2 > Set render engine to EEVEE > Try to spawn any block or item

### What version of MCprep are you using?

MCprep 3.5.3 and MCprep 3.6 RC-1

### What version of Blender are you using?

Blender 4.2

**Comment by zNightlord** [comment]
As far as I remember, Prep Material has an engine check which ever Eevee (legacy) or Cycles => work, else no.

**Comment by StandingPadAnimations** [comment]
We don't support EEVEE Next at the moment, as it's not yet stable. EEVEE Next support will be added once it's available in a stable release of Blender.

**Comment by StandingPadAnimations** [comment]
Not marking as a bug for now

**Comment by Aspirata** [comment]
Why don't you change this to if eevee or cycles then work, else generate standard material. Also, I don't see any difference in materials, so why does this check even exist ?

**Comment by StandingPadAnimations** [comment]
In MCprep, we check for either Cycles, Workbench, or EEVEE. If the currently set engine is not one of those 3 and is 3rd party (ex. Luxcore, Octane, Renderman, etc.), we don't generate materials, since we simply don't support them.

EEVEE Next and EEVEE Legacy have different internal names; EEVEE Next is referred to as `BLENDER_EEVEE_NEXT`, and EEVEE Legacy is referred to as `BLENDER_EEVEE`. Since `BLENDER_EEVEE_NEXT` is not in the list of supported engines for MCprep (*because it simply didn't exist when we created the list*), MCprep *think* EEVEE Next is an unsupported, 3rd party engine.

EEVEE Next will be added to the support list once it becomes part of stable Blender (i.e. not an alpha or beta build)

**Comment by Aspirata** [comment]
Why then workbench is also unsupported ?

**Comment by StandingPadAnimations** [comment]
(Updated [earlier comment](https://github.com/Moo-Ack-Productions/MCprep/issues/583#issuecomment-2138058750))

Because none of MCprep's changes will make any meaningful difference in Workbench (which is the engine used for Solid view)

**Comment by zNightlord** [comment]
> Why then workbench is also unsupported ?

Hope you saw my "*And why even Workbench?"  Like It supposed not to be in here the first place. 
Also since this bring out the problem, beside Eevee Next there is another builtin render engine that was added in 4.0, it is better to ignore Hydra Storm because it is near the level of Workbench but since it is somewhat builtin so...

**Comment by Aspirata** [comment]
k

**Comment by StandingPadAnimations** [comment]
Closing this since EEVEE Next is now supported in MCprep
